### ISSUE TITLE
Version 1.1.8 is published without lib directory

### ISSUE THREAD

**Issue by robrichard** [BohdanTkachenko/eslint-plugin-require-path-exists#36]
```
Oops! Something went wrong! :disappointed:

ESLint couldn't find the plugin "eslint-plugin-require-path-exists". This can happen for a couple different reasons:
```

It works with version 1.1.7

**Comment by eljefedelrodeodeljefe** [comment]
Same problem.

**Comment by coolchip** [comment]
Same here. When I'm running lint I get:
```
Cannot find module './lib'
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/username/myfancyproject/node_modules/eslint-plugin-require-path-exists/index.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Switching back to 1.1.7 resolving the problem

**Comment by hellatan** [comment]
@BohdanTkachenko any update on this?

**Comment by iamstarkov** [comment]
no-unresolved¹ rule of eslint-plugin-import² does the same, consider switching

\[1]: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md
\[2]: https://github.com/benmosher/eslint-plugin-import

**Comment by hellatan** [comment]
@iamstarkov i see you are a contributor here. Are you able to publish a patch to at least fix the broken 1.1.8 version?

**Comment by BohdanTkachenko** [comment]
I do not longer actively support this repo anymore, since I switched to [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) which already includes [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) which was mentioned by @iamstarkov , so please do switch.

Regarding to this bug, I just published version 1.1.9 which should fix this issue

**Comment by BohdanTkachenko** [comment]
Please also let me know if anyone still needs this package and wants to maintain it

**Comment by hellatan** [comment]
thank you @BohdanTkachenko. I'll look into migrating our configs to use the import ones instead.
